name: Build and Package
on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push API
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/api:${{ github.sha }},${{ secrets.DOCKER_REGISTRY }}/api:latest

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push UI
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/ui:${{ github.sha }},${{ secrets.DOCKER_REGISTRY }}/ui:latest

  package-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package Database Scripts
        run: tar -czf database-${{ github.sha }}.tar.gz database/
      - name: Upload Database Package
        uses: actions/upload-artifact@v3
        with:
          name: database-package
          path: database-${{ github.sha }}.tar.gz